### PR TITLE
fix: set cluster domain for credentials URIs

### LINKED ISSUE #110: Minibroker relies on the search path for the cluster domain
This behaviour will break when used with the next version of KubeCF with its custom apps-dns. This is because the Garden containers don't set the search path on `/etc/resolv.conf` when custom nameservers are provided.

What means for Minibroker is that instead of setting the URI in the credentials like `mysql.<namespace>.svc`, it will need to `mysql.<namespace>.svc.<cluster_domain>`. The cluster domain is not a constant (even though it's usually set to `cluster.local`). A way to determine it is by querying the `kubernetes.default.svc` from the Minibroker container that has the search path set by Kubernetes. E.g.:

```bash
awk 'match($0, /search.*\ssvc\.([a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}).*$/, cg) { print cg[1] }' /etc/resolv.conf
```

Since we don't have `awk`, we can use Go to read `/etc/resolv.conf` and perform the same regex match.

### PR DESCRIPTION
**Pull request by f0rmiga**
Fixes #110.

### CODE REVIEW

File: cmd/minibroker/main.go [hunk 1]
```diff
@@ -79,6 +82,18 @@ func main() {
 	})
 	defer klog.Flush()
 
+	if options.ClusterDomain == "" {
+		resolvConf, err := os.Open("/etc/resolv.conf")
+		if err != nil {
+			klog.Fatalln(err)
+		}
```
Comment (mook-as) [inline cmd/minibroker/main.go:89]: We should do a `defer resolvConfg.Close()` here instead (so that we'll do it correctly in the `klog.Fatalln()` case).

Yes, I'm aware that the file handle will be closed on process exit anyway.

File: pkg/broker/broker.go [hunk 2]
```diff
@@ -91,7 +91,7 @@ type MinibrokerClient interface {
 // Broker the parameters passed in.
 func NewBrokerFromOptions(o Options) (*Broker, error) {
 	klog.V(5).Infof("broker: creating a new broker with options %+v", o)
-	mb := minibroker.NewClient(o.ConfigNamespace, o.ServiceCatalogEnabledOnly)
+	mb := minibroker.NewClient(o.ConfigNamespace, o.ServiceCatalogEnabledOnly, o.ClusterDomain)
```
Comment (mook-as) [inline pkg/broker/broker.go:94]: It's getting to the point where passing in a struct there starts to look appealing (to ensure we don't pass arguments in the wrong order, by having named arguments).

File: pkg/broker/options.go [hunk 3]
```diff
@@ -26,4 +26,5 @@ type Options struct {
 	ServiceCatalogEnabledOnly bool
 	// The YAML file where the optional default chart values are stored.
 	ProvisioningSettingsPath string
+	ClusterDomain            string
```
Comment (mook-as) [inline pkg/broker/options.go:29]: Document please? Something like:
> The cluster domain of the Kubernetes cluster; typically `cluster.local`

File: pkg/kubernetes/cluster.go [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+package kubernetes
+
+import (
+	"fmt"
+	"io"
+	"io/ioutil"
+	"strings"
+)
+
+// ClusterDomain returns the k8s cluster domain extracted from the
```
Comment (mook-as) [inline pkg/kubernetes/cluster.go:26]:
```suggestion
// ClusterDomain returns the k8s cluster domain extracted from
```

File: pkg/kubernetes/cluster.go [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+// /etc/resolv.conf.
+func ClusterDomain(resolvConf io.Reader) (string, error) {
```
Comment (mook-as) [inline pkg/kubernetes/cluster.go:28]: Wouldn't it make more sense to pass in the result of `ioutil.ReadFile` instead? (I assume you're passing in the file here for ease of testing.)

Comment (mook-as) [reply pkg/kubernetes/cluster.go:28]: Also, would it make sense to use something like [github.com/containers/libpod/pkg/resolvconf](https://pkg.go.dev/github.com/containers/libpod/pkg/resolvconf) to do the parsing? Mostly because it (being part of podman and derived from docker) probably has seen enough `/etc/resolv.conf` files in the wild that it would be able to handle any unexpectedly weird configurations.

File: cmd/minibroker/main.go [hunk 6]
```diff
@@ -65,6 +66,8 @@ func main() {
 		"The default namespace for brokers when the request doesn't specify")
 	flag.StringVar(&options.ProvisioningSettingsPath, "provisioningSettings", "",
 		"The path to the YAML file where the optional provisioning settings are stored")
+	flag.StringVar(&options.ClusterDomain, "clusterDomain", "",
+		"The k8s cluster domain - it not set, Minibroker infers from /etc/resolv.conf")
```
Comment (f0rmiga) [inline cmd/minibroker/main.go:70]:
```suggestion
		"The k8s cluster domain - if not set, Minibroker infers from /etc/resolv.conf")
```

File: pkg/kubernetes/cluster.go [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+			searchLine = line
+		}
+	}
+
+	if searchLine == "" {
+		err := fmt.Errorf("missing the search path from resolv.conf")
+		return "", fmt.Errorf("failed to get cluster domain: %w", err)
+	}
+
+	domains := strings.Split(searchLine, " ")
```
Comment (mook-as) [inline pkg/kubernetes/cluster.go:47]:
```suggestion
	domains := strings.Fields(searchLine)
```

File: pkg/kubernetes/cluster.go [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+	for i := 1; i < len(domains); i++ {
```
Comment (mook-as) [inline pkg/kubernetes/cluster.go:48]:
```suggestion
	for range _, search := range domains {
```
We'll needlessly look at `search`, but that doesn't start with `svc.`; if we use the external library, that's fine too.

File: cmd/minibroker/main.go [hunk 9]
```diff
@@ -65,6 +66,8 @@ func main() {
 		"The default namespace for brokers when the request doesn't specify")
 	flag.StringVar(&options.ProvisioningSettingsPath, "provisioningSettings", "",
 		"The path to the YAML file where the optional provisioning settings are stored")
+	flag.StringVar(&options.ClusterDomain, "clusterDomain", "",
+		"The k8s cluster domain - if not set, Minibroker infers from /etc/resolv.conf")
```
Comment (mook-as) [inline cmd/minibroker/main.go:70]: Needs an example — should this be `cluster.local` or `.cluster.local`?

File: pkg/kubernetes/cluster_test.go [hunk 10]
```diff
@@ -0,0 +1,73 @@
...
+	. "github.com/onsi/gomega"
+
+	"github.com/kubernetes-sigs/minibroker/pkg/kubernetes"
+)
+
+var _ = Describe("Cluster", func() {
+	It("should fail when reading the resolv.conf reader fails", func() {
+		var resolvConf failReader
+		clusterDomain, err := kubernetes.ClusterDomain(&resolvConf)
+		Ω(clusterDomain).Should(BeZero())
```
Comment (mook-as) [inline pkg/kubernetes/cluster_test.go:33]: Please don't use Ω — it's hard to type on non-Mac machines and harder to read.

Comment (mook-as) [inline pkg/kubernetes/cluster_test.go:33]:
```suggestion
		Ω(clusterDomain).Should(BeEmpty())
```
While the zero value of a string _is_ the empty string, as English it reads much better as `BeEmpty`.

File: pkg/kubernetes/cluster_test.go [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+		fmt.Fprintln(&resolvConf, "nameserver 4.3.2.1")
+		fmt.Fprintln(&resolvConf, "search kubecf.svc.cluster.local svc.cluster.local cluster.local")
+		fmt.Fprintln(&resolvConf, "options ndots:5")
+		clusterDomain, err := kubernetes.ClusterDomain(&resolvConf)
+		Ω(clusterDomain).Should(Equal("cluster.local"))
+		Ω(err).ShouldNot(HaveOccurred())
+	})
+})
+
+type failReader struct{}
```
Comment (mook-as) [inline pkg/kubernetes/cluster_test.go:69]: Please add documentation for the type.

File: pkg/minibroker/provider.go [hunk 12]
```diff
@@ -148,6 +148,14 @@ func NewProvisionParams(m map[string]interface{}) *ProvisionParams {
 	return &ProvisionParams{Object: m}
 }
 
-func buildHostFromService(service corev1.Service) string {
-	return fmt.Sprintf("%s.%s.svc", service.Name, service.Namespace)
+// hostBuilder provides the method for building the OSBAPI service's URI host
+// from a k8s service.
```
Comment (mook-as) [inline pkg/minibroker/provider.go:152]: That's a bit jargon-heavy (I think I'm just having a reaction to `OSBAPI` being so close to `URI` and `k8s` and having to mentally expand them all).

**Review by mook-as — CHANGES_REQUESTED** [review]

File: cmd/minibroker/main.go (hunk 1 above)
Comment (f0rmiga) [reply cmd/minibroker/main.go:89]: Exactly, we don't need a defer for closing.

File: pkg/broker/broker.go (hunk 2 above)
Comment (f0rmiga) [reply pkg/broker/broker.go:94]: I follow the Law of Demeter. I won't pass the full object.

File: cmd/minibroker/main.go (hunk 9 above)
Comment (mook-as) [reply cmd/minibroker/main.go:70]: Yes, but it's always good to be clear on what's expected.  Having to re-deploy because there was a dumb mistake sucks.

File: pkg/broker/broker.go (hunk 2 above)
Comment (mook-as) [reply pkg/broker/broker.go:94]: I'm not asking you to pass in the full object; I'm asking for the arguments of the function to be a struct (that may or may not be the same struct).

File: pkg/broker/options.go (hunk 3 above)
Comment (f0rmiga) [reply pkg/broker/options.go]: Fixed with 4cf0d9b2a1bdea698ef206d4ff77fc6184ee39c2.

File: pkg/minibroker/provider.go (hunk 12 above)
Comment (f0rmiga) [reply pkg/minibroker/provider.go:152]: Open Service Broker API is no close to URI in any sense. Doesn't make sense at all to compare them.
I don't understand where the jargon is.

File: pkg/kubernetes/cluster_test.go (hunk 11 above)
Comment (f0rmiga) [reply pkg/kubernetes/cluster_test.go:69]: This is so so so so obvious ... ... ...

File: pkg/kubernetes/cluster.go (hunk 5 above)
Comment (f0rmiga) [reply pkg/kubernetes/cluster.go:28]: > Wouldn't it make more sense to pass in the result of ioutil.ReadFile instead? (I assume you're passing in the file here for ease of testing.)

I'm not passing it for easing the testing, but it helps, yes. I don't see any advantage of doing the reading ahead of time. So, I'll keep it as is.

> Also, would it make sense to use something like github.com/containers/libpod/pkg/resolvconf to do the parsing?

Makes sense! I'll bring it here.

File: pkg/broker/broker.go (hunk 2 above)
Comment (f0rmiga) [reply pkg/broker/broker.go:94]: I see your point. Creating a struct for 3 parameters sounds overkill...

File: cmd/minibroker/main.go (hunk 9 above)
Comment (f0rmiga) [reply cmd/minibroker/main.go:70]: I'm not even exposing this to the chart yet. I'd probably rely on a JSON schema validation if we ever end up exposing this to the chart. http://json-schema.org/understanding-json-schema/reference/regular_expressions.html

File: pkg/kubernetes/cluster_test.go (hunk 10 above)
Comment (f0rmiga) [reply pkg/kubernetes/cluster_test.go]: I use openSUSE (I work for SUSE - even if I didn't I'd probably still be using openSUSE) and I could copy-paste it! Let it be cool!

Comment (mook-as) [reply pkg/kubernetes/cluster_test.go]: No, let's not: I'm aiming for readability & ease of modification.

Speaking as somebody who _could_ (and sometimes does) type in a non-Latin language… Identifiers should still be in English.  Comments are more of a free-for-all, though.

File: cmd/minibroker/main.go (hunk 1 above)
Comment (mook-as) [reply cmd/minibroker/main.go:89]: But we do if we ever end up modifying this function later. If the language has a good construct for this, we should use it. (Otherwise it'd be `try`/`finally` or similar).

File: pkg/kubernetes/cluster.go (hunk 8 above)
Comment (mook-as) [reply pkg/kubernetes/cluster.go:37]: Err, this doesn't appear to have been fixed? By "if we use the external library" I just mean "we'll no longer have to worry about looking at the `search` word".

I'm not sure what happened to the "unresolve" button on GitHub.

**Review by mook-as — CHANGES_REQUESTED** [review]
Ω

File: cmd/minibroker/main.go (hunk 1 above)
Comment (f0rmiga) [reply cmd/minibroker/main.go:89]: Fair enough...

File: pkg/kubernetes/cluster.go (hunk 8 above)
Comment (f0rmiga) [reply pkg/kubernetes/cluster.go:37]: Oh dang, I forgot this part. Thanks for catching it!

Comment (f0rmiga) [reply pkg/kubernetes/cluster.go:37]: Fixed with 7262ee4.

File: pkg/kubernetes/cluster_test.go (hunk 10 above)
Comment (f0rmiga) [reply pkg/kubernetes/cluster_test.go]: Whatever. ffd8738

File: cmd/minibroker/main.go (hunk 1 above)
Comment (f0rmiga) [reply cmd/minibroker/main.go:89]: Fixed in b82d19f.

**Review by mook-as — APPROVED** [review]
/lgtm

File: cmd/minibroker/main.go (hunk 1 above)
Comment (f0rmiga) [reply cmd/minibroker/main.go:89]: Let's be clear, the `.Close()` that matter is not the `defer` one because the `defer` only gets called on Minibroker termination.

File: tests/integration/testutil/helm.go [hunk 13]
```diff
@@ -31,19 +34,49 @@ func NewHelm(ns string) Helm {
...
 
-func (h Helm) Install(name, chart string) error {
-	cmd := exec.Command("helm", "install", name, chart, "--namespace", h.namespace, "--wait")
-	err := cmd.Run()
-	if err != nil {
+func (h Helm) Install(stdout, stderr io.Writer, name, chart string) error {
+	cmd := exec.Command(
+		"helm", "install", name, chart,
+		"--wait",
+		"--timeout", "15m",
```
Comment (mook-as) [inline tests/integration/testutil/helm.go:41]: Would be nice to make this configurable (for CI); but that's not a blocker.

File: tests/integration/testutil/helm.go [hunk 14]
```diff
@@ -31,19 +34,49 @@ func NewHelm(ns string) Helm {
...
+	)
+	cmd.Stdout = stdout
+	cmd.Stderr = stderr
+
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	// Start a goroutine to print a waiting message every minute. It stops when
+	// the 'cancel' function is called, which is after the Helm command exits
+	// successfully or not.
```
Comment (mook-as) [inline tests/integration/testutil/helm.go:52]:
```suggestion
	// (whether it was successful or not).
```

**Review by mook-as — APPROVED** [review]
👍 just some nits

**Review by mook-as — APPROVED** [review]
/lgtm
